name: Test

on:
  push:
    branches: ["test"]
  pull_request:
    branches: ["test"]

permissions:
  contents: read

jobs:
  deno-test:
    if: always()
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        deno: [ 2.2.11, rc, canary ]

    steps:
      - name: Setup repo
        if: always()
        uses: actions/checkout@v4

      - name: Setup Deno
        if: always()
        uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}

      - name: Run tests
        if: always()
        run: deno test --allow-all

  node-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - name: Setup repo
        if: always()
        uses: actions/checkout@v4

      - name: Setup Node.js
        if: always()
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Run tests
        if: always()
        run: node --test
